INSERT INTO inmueble (nombre, direccion, pais, codigo_postal, municipio_alcaldia, prefijo, capacidad) VALUES 
('Estadio GNP Seguros', 'Viaducto Piedad y Río Churubusco s/n Cd. Deportiva', 'México', '08400', 'Ciudad de México', 'EST', 62466),
('Autodromo Hnos. Rodriguez', 'Viaducto Piedad y Río Churubusco s/n Cd. Deportiva', 'México', '08400', 'México', 'AUT', 72747),
('Teatro de la Ciudad Esperanza Iris', 'Donceles #36, Col. Centro Historico', 'México', '08400', 'Mexico', 'TEA', 2976),
('Teatro Estudio Cavaret', 'Av. Parres Arias esquina Periférico Frente a Belenes', 'México', '44630', 'Zapopan', 'TEA', 2918),
('La Maraka', 'Mitla #410 esq. Eje 5 Sur Eugenia, Col. Narvarte', 'México', '03600', 'México', 'LAM', 4034),
('Auditorio Banamex', 'Privada Fundidora s/n Col. Obrera', 'México', '64010', 'Monterrey', 'AUD', 12353),
('Teatro Tepeyac', 'Calz.de Guadalupe #497 Col. Estrella', 'México', '07810', 'México', 'TEA', 2788),
('Auditorio Telmex', 'Obreros de Cananea # 747, Col. Villas de los Belenes', 'México', '45192', 'Zapopan', 'AUD', 12683),
('Teatro Diana (GDL)', 'Av. 16 de Septiembre No. 710, Zona Centro', 'México', '44630', 'Guadalajara', 'TEA', 2998),
('Foro Tims', 'Av. Constitucion', 'México', '64000', 'Col. Centro Monterrey', 'FOR', 2626),
('Centro Cultural Teatro II', 'Av. Chapultepec y Av. Cuauhtémoc', 'México', '06700', 'México', 'CEN', 2595),
('Teatro Metropolitan', 'Independencia #90 Col. Centro, entre las calles de Balderas', 'México', '06050', 'México', 'TEA', 2325),
('Pabellón del Palacio de los Deportes', 'Av. Río Churubusco y Añil s/n Col. Granjas México', 'México', '08400', 'México', 'PAB', 12834),
('Foro Puebla', 'Puebla No 186 esq. Insurgentes', 'México', '06700', 'Mexico', 'FOR', 2508),
('Auditorio BB', 'Av. Insurgentes Sur #453, Col. Hipódromo', 'México', '06100', 'México', 'AUD', 13902),
('Velodromo', 'Col. Jardín Balbuena, Alc. Venustiano Carranza', 'México', '15900', 'Ciudad de México', 'VEL', 2566),
('Palacio de los Deportes', 'Av. Río Churubusco y Añil s/n Col. Granjas México', 'México', '08400', 'Ciudad de México', 'PAL', 14996),
('Foro Red Access', 'Avenida Centenario 159', 'México', '04100', 'México', 'FOR', 1225),
('Auditorio Nacional', 'Paseo de la Reforma # 50 Col Polanco V Sección', 'México', '11560', 'Ciudad de México', 'AUD', 21883),
('Teatro Benito Juárez', 'Villalongin No. 15, Col. Cuauhtémoc', 'México', '08400', 'México', 'TEA', 1359),
('Estudio Diana', 'Av. 16 de Septiembre #710, Zona Centro', 'México', '44630', 'Guadalajara', 'EST', 1383),
('El Lunario del Auditorio Nacional', 'Costado poniente del Auditorio Nacional frente al Campo', 'México', '11560', 'Ciudad de México', 'ELL', 19294),
('Pepsi Center WTC', 'Dakota S/N, Colonia Nápoles', 'México', '03810', 'México', 'PEP', 2122),
('Nave Lewis', 'Av. Adolfo Prieto S/N', 'México', '64010', 'Monterrey', 'NAV', 2550),
('Escenario GNP Seguros', 'Av. Benito Juárez No. 1002', 'México', '64000', 'Monterrey', 'ESC', 83702),
('Nenue test MTY', 'Sin dirección', 'México', '90028', 'Los Angeles', 'NEN', 4442),
('VENUE TEST 78 GDL', 'QPWZL - VENUE TEST 78 GDL', 'México', '90028', 'Los Angeles', 'VEN', 3591),
('Sala Silvestre Revueltas', 'Periférico Sur #5141 Col. Isidro Fabela', 'México', '14030', 'México', 'SAL', 2064),
('Sede Stage', 'Av. Adolfo Lopez Mateos Sur 9020-A', 'México', '45645', 'Tlajomulco de Zuñija', 'SED', 4459),
('Arena VFG', 'Rancho Los 3 Potrillos, Km 20 carretera a Chapala', 'México', '44630', 'Tlajomulco de Zuñiga', 'ARE', 15791),
('Grand Mambo Cafe Tlalnepantla', 'Av. Gustavo Baz Prada 166, Col La Escuela', 'México', '54090', 'Tlalnepantla de Baz', 'GRA', 4650),
('Arena GNP', 'Paseo de los Manglares 1007, Granjas del Marqués', 'México', '39890', 'Acapulco de Juárez', 'ARE', 31433),
('El Cantoral', 'Puente de Xoco puerta A', 'México', '03330', 'Mexico', 'ELC', 1397),
('Mambo Cafe Insurgentes', 'Insurgentes Sur #644', 'México', '03100', 'México', 'MAM', 2277),
('Monumental Plaza De Toros México', 'Augusto Rodin #241 Col. Ciudad de los Deportes', 'México', '07810', 'México', 'MON', 1359),
('Nuevo Teatro Libanés', 'Barranca Del Muerto y 2 de Abril, Col. Crédito Constructor', 'México', '03940', 'México', 'NUE', 1403),
('Estadio Olimpico Universitario Club Cruz Azul', 'Av. Insurgentes Sur s/n Ciudad Universitaria', 'México', '04510', 'México', 'EST', 53843),
('Estadio BBVA', 'Av. Pablo Livas No. 2011', 'México', '67140', 'Guadalupe', 'EST', 36615),
('Estadio Olimpico Universitario', 'Av. Insurgentes Sur s/n Ciudad Universitaria', 'México', '04510', 'México', 'EST', 53684),
('Estadio Tomateros', 'Avenida Jesus Andrade S/N, Miguel Aleman', 'México', '80200', 'Culiacan Rosales', 'EST', 39267),
('Estadio Alfredo Harp Helú', 'Av. Rio Churubusco 1001', 'México', '08010', 'Ciudad de México', 'EST', 66371),
('Arena México', 'Dr. Lavista No. 197 Col. Doctores', 'México', '06720', 'México', 'ARE', 10874),
('Arena Coliseo de Guadalajara', 'Medrano #67', 'México', '44100', 'Guadalajara', 'ARE', 21614),
('Arena Coliseo', 'Perú #77 Col. Centro', 'México', '06700', 'México', 'ARE', 12829),
('Arena Puebla', '13 oriente #402', 'México', '72000', 'Puebla', 'ARE', 13535),
('Plaza De Toros Nuevo Progreso', 'Montes Pirineos s/n Col. Monumental', 'México', '44630', 'Guadalajara', 'PLA', 4139),
('Teatro Coyoacán Enrique Lizalde', 'Eleuterio Méndez #11 Colonia San Mateo Churubusco', 'México', '04120', 'Ciudad de México', 'TEA', 2283),
('Foro Lucerna', 'Calle Lucerna. No. 64 Esquina con calle Milán', 'México', '06600', 'México', 'FOR', 3522),
('Teatro Milán', 'Calle Lucerna. No. 64 Esquina con calle Milán', 'México', '06600', 'México', 'TEA', 825),
('Teatro de los Insurgentes', 'Insurgentes Sur #1587', 'México', '03900', 'México', 'TEA', 2006),
('Teatro Varsovia', 'Varsovia 9, Juarez, Cuauhtemoc', 'México', '06600', 'Ciudad de Mexico', 'TEA', 1617),
('Teatro Telcel', 'Lago Zurich #245, Primer Piso', 'México', '11529', 'México', 'TEA', 1683),
('Teatro SOGEM Wilberto Cantón', 'José María Velasco #59, Col. San José Insurgentes', 'México', '03900', 'México', 'TEA', 2320),
('Teatro Xola Julio Prieto', 'Eje 4 Sur Xola #809 esq. Nicolás San Juan Col. Del Valle', 'México', '08400', 'México', 'TEA', 2235),
('Palacio de Bellas Artes', 'Av Juárez, Centro Histórico, Centro', 'México', '06050', 'México CDMX', 'PAL', 10887),
('Teatro del Pueblo', 'República de Venezuela 72, Centro Histórico de la Ciudad', 'México', '06010', 'Ciudad de Mexico', 'TEA', 891),
('Centro Cultural San Angel', 'Revolución Esq. Madero, Col. San Ángel', 'México', '08400', 'México', 'CEN', 3854),
('Sala Manuel M. Ponce - Palacio de Bellas Artes', 'Av. Hidalgo #1, Col. Centro,', 'México', '06050', 'México', 'SAL', 17596),
('Teatro Aldama', 'Rosas Moreno #71 Col. San Rafael', 'México', '06470', 'México', 'TEA', 2199),
('FORO A POCO NO', 'República de Cuba 49 (entre República de Chile y Allende)', 'México', '06010', 'México', 'FOR', 1812),
('Teatro Virginia Fábregas', 'Velásquez de León #31 Col. San Rafael', 'México', '06470', 'México', 'TEA', 2666),
('Foro Cultural Chapultepec', 'Mariano Escobedo #665, Col. Anzures', 'México', '11590', 'México', 'FOR', 1934),
('GRAN CARPA SANTA FE', 'Av. Vasco De Quiroga No. 2000, Col. Santa Fe', 'México', '05300', 'México', 'GRA', 3130),
('Teatro Renacimiento (CTMF)', 'Velázquez de León #31, Col. San Rafael', 'México', '06470', 'México', 'TEA', 1462),
('Teatro Mexico (CTMF)', 'Velásquez de León #31 Col. San Rafael', 'México', '06470', 'México', 'TEA', 2020),
('Teatro Fernando Soler (CTMF)', 'Velásquez de León #31 Col. San Rafael', 'México', '06470', 'México', 'TEA', 2511),
('Teatro Jorge Negrete', 'Ignacio M. Altamirano #126. Col. San Rafael', 'México', '06470', 'México', 'TEA', 2435),
('Teatro del Bicentenario', 'Prol. Calzada de los Héroes #308', 'México', '37500', 'Leon', 'TEA', 1429),
('Teatro Hidalgo', 'Av. Hidalgo #23 Col. Centro', 'México', '06050', 'México', 'TEA', 854),
('Foro Rodolfo Usigli', 'Eleuterio Mendez 11 Colonia San Mateo Churubusco', 'México', '04120', 'Mexico', 'FOR', 3688),
('Teatro Rafael Solana', 'Miguel Ángel de Quevedo #687 Col. Coyoacán', 'México', '06470', 'México', 'TEA', 1036),
('Teatro 11 de Julio', 'Doctor Vertiz #668 Col. Narvarte', 'México', '08400', 'México', 'TEA', 2236),
('Teatro Broadway', 'Joaquín Velázquez de León No.31', 'México', '06470', 'Cuauhtémoc', 'TEA', 1542),
('Teatro Ofelia', 'Thiers 287, Esq. con Ejercito Nacional', 'México', '11590', 'México', 'TEA', 2638),
('Teatro Ferrocarrilero', 'Calz. Ricardo Flores Magón #206 entre Guerrero y', 'México', '06300', 'México', 'TEA', 1533),
('Telón de Asfalto', 'Perpetua #4 esq. Insurgentes Sur', 'México', '03310', 'México', 'TEL', 3608),
('Teatro San Jerónimo Independencia', 'Periférico Sur #3400 Unidad Independencia', 'México', '10100', 'México', 'TEA', 1686),
('Forum de Mundo Imperial', 'Blvd. de las Naciones s/n esq. Blvd. de Barra Vieja', 'México', '39900', 'Acapulco', 'FOR', 3939),
('Aula Magna', 'Av. Revolucion 1500, Guadalupe Inn, Alvaro Obregón', 'México', '01020', 'Ciudad de México', 'AUL', 1091),
('Castillo de Chapultepec', 'Primera sección del Bosque de Chapultepec', 'México', '08400', 'México', 'CAS', 2917),
('Teatro Royal Pedregal', 'Periférico Sur 4363', 'México', '14210', 'México', 'TEA', 2646),
('Teatro Galerías', 'Av. Lapizlázuli #3445', 'México', '45050', 'Zapopan', 'TEA', 2211),
('TEATRO SERGIO MAGAÑA', 'Sor Juana Inés de la Cruz 114', 'México', '06400', 'México', 'TEA', 1414),
('Centro Cultural Teatro I', 'Av. Chapultepec y Av. Cuauhtémoc', 'México', '06700', 'México', 'CEN', 2245),
('Auditorio Mateo Herrera', 'Prolongación Calzada #308 Esq. Vasco de Quiroga', 'México', '37500', 'León', 'AUD', 18020),
('Hosteria del Convento de Tepotzotlán', 'Plaza Virreinal # 1', 'México', '54600', 'Tepotzotlán', 'HOS', 1111),
('Auditorio Luis Elizondo', 'Av. Luis Elizondo No. 540 Col. Tecnológico', 'México', '64010', 'Monterrey', 'AUD', 17744),
('Nuevo Teatro Silvia Pinal', 'C. Versalles 27, Juárez, Cuauhtémoc', 'México', '06600', 'Ciudad de México', 'NUE', 2398),
('Teatro Centenario Coyoacan', 'Avenida Centenario 159', 'México', '04100', 'Ciudad de Mexico', 'TEA', 1446),
('Parque Xtremo', 'Aerodromo de Atlixco', 'México', '74365', 'Atlixco', 'PAR', 3858),
('Parque Fundidora', 'Av. Fundidora s/n Col. Obrera', 'México', '61010', 'Monterrey', 'PAR', 3084),
('Baja Beach', 'Coronado 400', 'México', '22710', 'Rosarito', 'BAJ', 4064)
ON CONFLICT DO NOTHING;

-- PLANOS
INSERT INTO plano (nombre, mapa, inmueble_id) VALUES 
('Plano General Estadio GNP Seguros', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Estadio GNP Seguros' LIMIT 1)),
('Plano General Autodromo Hnos. Rodriguez', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Autodromo Hnos. Rodriguez' LIMIT 1)),
('Plano General Teatro de la Ciudad Esperanza Iris', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro de la Ciudad Esperanza Iris' LIMIT 1)),
('Plano General Teatro Estudio Cavaret', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Estudio Cavaret' LIMIT 1)),
('Plano General La Maraka', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'La Maraka' LIMIT 1)),
('Plano General Auditorio Banamex', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Auditorio Banamex' LIMIT 1)),
('Plano General Teatro Tepeyac', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Tepeyac' LIMIT 1)),
('Plano General Auditorio Telmex', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Auditorio Telmex' LIMIT 1)),
('Plano General Teatro Diana (GDL)', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Diana (GDL)' LIMIT 1)),
('Plano General Foro Tims', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Foro Tims' LIMIT 1)),
('Plano General Centro Cultural Teatro II', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Centro Cultural Teatro II' LIMIT 1)),
('Plano General Teatro Metropolitan', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Metropolitan' LIMIT 1)),
('Plano General Pabellón del Palacio de los Deportes', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Pabellón del Palacio de los Deportes' LIMIT 1)),
('Plano General Foro Puebla', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Foro Puebla' LIMIT 1)),
('Plano General Auditorio BB', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Auditorio BB' LIMIT 1)),
('Plano General Velodromo', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Velodromo' LIMIT 1)),
('Plano General Palacio de los Deportes', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Palacio de los Deportes' LIMIT 1)),
('Plano General Foro Red Access', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Foro Red Access' LIMIT 1)),
('Plano General Auditorio Nacional', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Auditorio Nacional' LIMIT 1)),
('Plano General Teatro Benito Juárez', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Benito Juárez' LIMIT 1)),
('Plano General Estudio Diana', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Estudio Diana' LIMIT 1)),
('Plano General El Lunario del Auditorio Nacional', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'El Lunario del Auditorio Nacional' LIMIT 1)),
('Plano General Pepsi Center WTC', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Pepsi Center WTC' LIMIT 1)),
('Plano General Nave Lewis', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Nave Lewis' LIMIT 1)),
('Plano General Escenario GNP Seguros', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Escenario GNP Seguros' LIMIT 1)),
('Plano General Nenue test MTY', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Nenue test MTY' LIMIT 1)),
('Plano General VENUE TEST 78 GDL', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'VENUE TEST 78 GDL' LIMIT 1)),
('Plano General Sala Silvestre Revueltas', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Sala Silvestre Revueltas' LIMIT 1)),
('Plano General Sede Stage', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Sede Stage' LIMIT 1)),
('Plano General Arena VFG', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Arena VFG' LIMIT 1)),
('Plano General Grand Mambo Cafe Tlalnepantla', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Grand Mambo Cafe Tlalnepantla' LIMIT 1)),
('Plano General Arena GNP', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Arena GNP' LIMIT 1)),
('Plano General El Cantoral', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'El Cantoral' LIMIT 1)),
('Plano General Mambo Cafe Insurgentes', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Mambo Cafe Insurgentes' LIMIT 1)),
('Plano General Monumental Plaza De Toros México', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Monumental Plaza De Toros México' LIMIT 1)),
('Plano General Nuevo Teatro Libanés', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Nuevo Teatro Libanés' LIMIT 1)),
('Plano General Estadio Olimpico Universitario Club Cruz Azul', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Estadio Olimpico Universitario Club Cruz Azul' LIMIT 1)),
('Plano General Estadio BBVA', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Estadio BBVA' LIMIT 1)),
('Plano General Estadio Olimpico Universitario', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Estadio Olimpico Universitario' LIMIT 1)),
('Plano General Estadio Tomateros', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Estadio Tomateros' LIMIT 1)),
('Plano General Estadio Alfredo Harp Helú', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Estadio Alfredo Harp Helú' LIMIT 1)),
('Plano General Arena México', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Arena México' LIMIT 1)),
('Plano General Arena Coliseo de Guadalajara', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Arena Coliseo de Guadalajara' LIMIT 1)),
('Plano General Arena Coliseo', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Arena Coliseo' LIMIT 1)),
('Plano General Arena Puebla', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Arena Puebla' LIMIT 1)),
('Plano General Plaza De Toros Nuevo Progreso', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Plaza De Toros Nuevo Progreso' LIMIT 1)),
('Plano General Teatro Coyoacán Enrique Lizalde', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Coyoacán Enrique Lizalde' LIMIT 1)),
('Plano General Foro Lucerna', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Foro Lucerna' LIMIT 1)),
('Plano General Teatro Milán', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Milán' LIMIT 1)),
('Plano General Teatro de los Insurgentes', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro de los Insurgentes' LIMIT 1)),
('Plano General Teatro Varsovia', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Varsovia' LIMIT 1)),
('Plano General Teatro Telcel', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Telcel' LIMIT 1)),
('Plano General Teatro SOGEM Wilberto Cantón', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro SOGEM Wilberto Cantón' LIMIT 1)),
('Plano General Teatro Xola Julio Prieto', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Xola Julio Prieto' LIMIT 1)),
('Plano General Palacio de Bellas Artes', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Palacio de Bellas Artes' LIMIT 1)),
('Plano General Teatro del Pueblo', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro del Pueblo' LIMIT 1)),
('Plano General Centro Cultural San Angel', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Centro Cultural San Angel' LIMIT 1)),
('Plano General Sala Manuel M. Ponce - Palacio de Bellas Artes', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Sala Manuel M. Ponce - Palacio de Bellas Artes' LIMIT 1)),
('Plano General Teatro Aldama', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Aldama' LIMIT 1)),
('Plano General FORO A POCO NO', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'FORO A POCO NO' LIMIT 1)),
('Plano General Teatro Virginia Fábregas', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Virginia Fábregas' LIMIT 1)),
('Plano General Foro Cultural Chapultepec', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Foro Cultural Chapultepec' LIMIT 1)),
('Plano General GRAN CARPA SANTA FE', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'GRAN CARPA SANTA FE' LIMIT 1)),
('Plano General Teatro Renacimiento (CTMF)', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Renacimiento (CTMF)' LIMIT 1)),
('Plano General Teatro Mexico (CTMF)', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Mexico (CTMF)' LIMIT 1)),
('Plano General Teatro Fernando Soler (CTMF)', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Fernando Soler (CTMF)' LIMIT 1)),
('Plano General Teatro Jorge Negrete', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Jorge Negrete' LIMIT 1)),
('Plano General Teatro del Bicentenario', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro del Bicentenario' LIMIT 1)),
('Plano General Teatro Hidalgo', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Hidalgo' LIMIT 1)),
('Plano General Foro Rodolfo Usigli', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Foro Rodolfo Usigli' LIMIT 1)),
('Plano General Teatro Rafael Solana', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Rafael Solana' LIMIT 1)),
('Plano General Teatro 11 de Julio', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro 11 de Julio' LIMIT 1)),
('Plano General Teatro Broadway', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Broadway' LIMIT 1)),
('Plano General Teatro Ofelia', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Ofelia' LIMIT 1)),
('Plano General Teatro Ferrocarrilero', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Ferrocarrilero' LIMIT 1)),
('Plano General Telón de Asfalto', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Telón de Asfalto' LIMIT 1)),
('Plano General Teatro San Jerónimo Independencia', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro San Jerónimo Independencia' LIMIT 1)),
('Plano General Forum de Mundo Imperial', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Forum de Mundo Imperial' LIMIT 1)),
('Plano General Aula Magna', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Aula Magna' LIMIT 1)),
('Plano General Castillo de Chapultepec', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Castillo de Chapultepec' LIMIT 1)),
('Plano General Teatro Royal Pedregal', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Royal Pedregal' LIMIT 1)),
('Plano General Teatro Galerías', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Galerías' LIMIT 1)),
('Plano General TEATRO SERGIO MAGAÑA', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'TEATRO SERGIO MAGAÑA' LIMIT 1)),
('Plano General Centro Cultural Teatro I', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Centro Cultural Teatro I' LIMIT 1)),
('Plano General Auditorio Mateo Herrera', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Auditorio Mateo Herrera' LIMIT 1)),
('Plano General Hosteria del Convento de Tepotzotlán', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Hosteria del Convento de Tepotzotlán' LIMIT 1)),
('Plano General Auditorio Luis Elizondo', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Auditorio Luis Elizondo' LIMIT 1)),
('Plano General Nuevo Teatro Silvia Pinal', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Nuevo Teatro Silvia Pinal' LIMIT 1)),
('Plano General Teatro Centenario Coyoacan', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Teatro Centenario Coyoacan' LIMIT 1)),
('Plano General Parque Xtremo', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Parque Xtremo' LIMIT 1)),
('Plano General Parque Fundidora', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Parque Fundidora' LIMIT 1)),
('Plano General Baja Beach', 'http://maps.com/default', (SELECT inmueble_id FROM inmueble WHERE nombre = 'Baja Beach' LIMIT 1))
ON CONFLICT DO NOTHING;