INSERT INTO grupo_evento (nombre_grupo, descripcion) VALUES 
('Bad Bunny - DeBÍ TiRAR MáS FOToS World Tour', 'Agrupación de eventos'),
('Dua Lipa', 'Agrupación de eventos'),
('T.A.T.U.', 'Agrupación de eventos'),
('Flor Bertotti', 'Agrupación de eventos'),
('Tributo a Queen & Oldies, con el grupo Smile of Queen', 'Agrupación de eventos'),
('Camilo Septimo', 'Agrupación de eventos'),
('School of Rock - The Musical', 'Agrupación de eventos'),
('Rigoberta Bandini', 'Agrupación de eventos'),
('The Rasmus', 'Agrupación de eventos'),
('DLD - Invitados Especiales Sussie 4', 'Agrupación de eventos'),
('Toto + Christopher Cross', 'Agrupación de eventos'),
('Navidad con The Beatles, con el grupo Morsa', 'Agrupación de eventos'),
('M2M', 'Agrupación de eventos'),
('Natalie Imbruglia', 'Agrupación de eventos'),
('My Chemical Romance Long Live: The Black Parade', 'Agrupación de eventos'),
('Big Time Rush', 'Agrupación de eventos'),
('Individual Electric Daisy Carnival 2026 General', 'Agrupación de eventos'),
('Individual Electric Daisy Carnival 2026 Banamex Plus', 'Agrupación de eventos'),
('Individual Electric Daisy Canival 2026 Comfort Pass', 'Agrupación de eventos'),
('Kali Uchis', 'Agrupación de eventos'),
('Lenny Kravitz', 'Agrupación de eventos'),
('MARINA: The Princess of Power Tour', 'Agrupación de eventos'),
('Jason Mraz: Return to Mexico Tour', 'Agrupación de eventos'),
('Djo', 'Agrupación de eventos'),
('Soda Stereo', 'Agrupación de eventos'),
('P!NK', 'Agrupación de eventos'),
('Lorde - Ultrasound', 'Agrupación de eventos'),
('Mon Laferte', 'Agrupación de eventos'),
('RUSH', 'Agrupación de eventos'),
('José Luis Rodríguez "El Puma" y Enrique Guzmán', 'Agrupación de eventos'),
('The Neighbourhood: THE WOURLD TOUR', 'Agrupación de eventos'),
('J Balvin', 'Agrupación de eventos'),
('Caifanes', 'Agrupación de eventos'),
('Alberto Barros', 'Agrupación de eventos'),
('Los Angeles Azules', 'Agrupación de eventos'),
('Emmanuel & Mijares', 'Agrupación de eventos'),
('Silvana Estrada', 'Agrupación de eventos'),
('Yandel Sinfónico', 'Agrupación de eventos'),
('Eladio Carrion', 'Agrupación de eventos'),
('La máquina del tiempo - JUNTOS', 'Agrupación de eventos'),
('Raúl Ornelas', 'Agrupación de eventos'),
('Matisse', 'Agrupación de eventos'),
('Juanes', 'Agrupación de eventos'),
('Panteon Rococo', 'Agrupación de eventos'),
('Raphael', 'Agrupación de eventos'),
('Chayanne', 'Agrupación de eventos'),
('David Zahan', 'Agrupación de eventos'),
('Eliades Ochoa', 'Agrupación de eventos'),
('Bosé', 'Agrupación de eventos'),
('Gilberto Santa Rosa', 'Agrupación de eventos'),
('AC/DC - POWER UP TOUR 2026', 'Agrupación de eventos'),
('Softbol Charros de Jalisco v. Diablos Rojos Temporada 2026', 'Agrupación de eventos'),
('Softbol Naranjeros de Hermosillo v. Diablos Rojos Temporada 2026', 'Agrupación de eventos'),
('Softbol Sultanes de Monterrey v. Diablos Rojos Temporada 2026', 'Agrupación de eventos'),
('Softbol El Aguila de Veracruz v. Diablos Rojos Temporada 2026', 'Agrupación de eventos'),
('Softbol Olmecas de Tabasco v. Diablos Rojos Temporada 2026', 'Agrupación de eventos'),
('Softbol Bravas de Leon v. Diablos Rojos Temporada 2026', 'Agrupación de eventos'),
('Martes Populares de Lucha Libre CMLL', 'Agrupación de eventos'),
('Martes de Glamour, Lucha libre CMLL', 'Agrupación de eventos'),
('Viernes Espectacular de Lucha Libre CMLL', 'Agrupación de eventos'),
('Sábados de lucha libre CMLL', 'Agrupación de eventos'),
('Domingo Familiar de Lucha Libre CMLL', 'Agrupación de eventos'),
('Lucha Libre CMLL', 'Agrupación de eventos'),
('El Hijo del Santo La Despedida', 'Agrupación de eventos'),
('Conversando con el Diablo', 'Agrupación de eventos'),
('Las Mama´s Presentan: Noche de Juegos', 'Agrupación de eventos'),
('El pecado mejor cometido', 'Agrupación de eventos'),
('El Fantasma de la Ópera', 'Agrupación de eventos'),
('El Rey León', 'Agrupación de eventos'),
('Homenaje a Beckett', 'Agrupación de eventos'),
('La Casa de Bernarda de Alba', 'Agrupación de eventos'),
('Ballet Folklórico de México de Amalia Hernández. Ingreso 20:00 h.', 'Agrupación de eventos'),
('Esquizofrenia', 'Agrupación de eventos'),
('Loco Amor', 'Agrupación de eventos'),
('Godspell', 'Agrupación de eventos'),
('Asesinato para dos', 'Agrupación de eventos'),
('Próxima Estación: La Ciudad de las Jacarandas', 'Agrupación de eventos'),
('Razones para decirte adiós', 'Agrupación de eventos'),
('Toc Toc', 'Agrupación de eventos'),
('Mentidrags', 'Agrupación de eventos'),
('Zoo Cabaret', 'Agrupación de eventos'),
('Los monólogos de la vagina', 'Agrupación de eventos'),
('12 Princesas En Pugna', 'Agrupación de eventos'),
('Cómo Quieras... ¡Perro Ámame!', 'Agrupación de eventos'),
('El Juego Que Todos Jugamos', 'Agrupación de eventos'),
('La Obra Que Sale Mal', 'Agrupación de eventos'),
('Desconectadxs - Fundación Teatral Davar A.C.', 'Agrupación de eventos'),
('Las Meninas Novohispanas, serie 1: Un cuento de navidad', 'Agrupación de eventos'),
('Harry Potter: Visions of Magic', 'Agrupación de eventos'),
('La obscenidad de la carne.', 'Agrupación de eventos'),
('Las Leonas', 'Agrupación de eventos'),
('Alejandro Speitzer en Cruise', 'Agrupación de eventos'),
('El Sótano', 'Agrupación de eventos'),
('Dos Locas de Remate', 'Agrupación de eventos'),
('Por la Punta de la Nariz', 'Agrupación de eventos'),
('El tenorio comico', 'Agrupación de eventos'),
('Qué desastre de función', 'Agrupación de eventos'),
('Mentiras el Musical', 'Agrupación de eventos'),
('El Cascanueces', 'Agrupación de eventos'),
('¡A Vivir! de Odin Dupeyron', 'Agrupación de eventos'),
('Una Navidad Espectacular en Broadway en concierto', 'Agrupación de eventos'),
('El Diario de un Loco', 'Agrupación de eventos'),
('Infierno', 'Agrupación de eventos'),
('F**king Men', 'Agrupación de eventos'),
('La Dama De Negro', 'Agrupación de eventos'),
('Ni con ellas, ni sin ellas', 'Agrupación de eventos'),
('LMP El Episodio Maldito', 'Agrupación de eventos'),
('La Risa Mañanera', 'Agrupación de eventos'),
('Afterglow', 'Agrupación de eventos'),
('Rodolfo el Reno, un musical con un brillo singular', 'Agrupación de eventos'),
('Lo Que Queda de Nosotros', 'Agrupación de eventos'),
('El Grinch, un cuento musical', 'Agrupación de eventos'),
('Un Cuento de Navidad, el señor Scrooge', 'Agrupación de eventos'),
('Frosty un Muneco de Nieve el Musical', 'Agrupación de eventos'),
('El cuarto Rey Mago', 'Agrupación de eventos'),
('Un Cuento VHS de Navidad', 'Agrupación de eventos'),
('Busco al hombre de mi vida, marido ya tuve', 'Agrupación de eventos'),
('El Diario de Ana Frank', 'Agrupación de eventos'),
('El Cascanueces, Ballet', 'Agrupación de eventos'),
('Así Lo Veo Yo: Monólogo René Dupeyron', 'Agrupación de eventos'),
('La Pastorela del Bienestar', 'Agrupación de eventos'),
('Ballet Folklórico de México de Amalia Hernández. Ingreso 09:00 h.', 'Agrupación de eventos'),
('El Maravilloso Mago de Oz - Multimedia Teatro', 'Agrupación de eventos'),
('Ringolingus - Circo de sueños, magia y criaturas fantasticas', 'Agrupación de eventos'),
('Un Elfo Travieso', 'Agrupación de eventos'),
('El Soldadito de Plomo Un Musical Navideno', 'Agrupación de eventos'),
('Un reencuentro con la Navidad', 'Agrupación de eventos'),
('GINGER La galletita navidena el musical', 'Agrupación de eventos'),
('La historia de Gazapo', 'Agrupación de eventos'),
('Santa Claus...y el significado de la Navidad', 'Agrupación de eventos'),
('Personas, Lugares y Cosas', 'Agrupación de eventos'),
('Defendiendo al cavernícola', 'Agrupación de eventos'),
('DAHMER, Mirando a la bestia a los ojos', 'Agrupación de eventos'),
('Prendeme el Musical', 'Agrupación de eventos'),
('Ballet Nacional Ruso de Sergey Radchenko "El Cascanueces"', 'Agrupación de eventos'),
('Compañía Nacional de Ópera "La leyenda de Rudel" 10+. Ingreso 19:30 h.', 'Agrupación de eventos'),
('Tenorio Comico', 'Agrupación de eventos'),
('Cine Z', 'Agrupación de eventos'),
('Monólogos de la Lonja', 'Agrupación de eventos'),
('La Nota', 'Agrupación de eventos'),
('Navidad en las películas', 'Agrupación de eventos'),
('Las Mamás Presentan: Una noche de Navidad', 'Agrupación de eventos'),
('Franco Escamilla Presenta Show 1995', 'Agrupación de eventos'),
('Descubriendo a Cri Cri', 'Agrupación de eventos'),
('El Cascanueces: Centro Cultural Ollin Yoliztli', 'Agrupación de eventos'),
('Pastorcillos a Belen El Musical', 'Agrupación de eventos'),
('Feliz Navitrouppe', 'Agrupación de eventos'),
('INTERESTELLAR 11o. ANIVERSARIO MOVIE CONCERT', 'Agrupación de eventos'),
('Escuela De Danza Youcef Presenta "Lumina, Bailarinas de Luz"', 'Agrupación de eventos'),
('Las Famosas Pastorelas de Tepotzotlán', 'Agrupación de eventos'),
('TINA - The Tina Turner Musical', 'Agrupación de eventos'),
('Furias', 'Agrupación de eventos'),
('Navidad Sinfónica', 'Agrupación de eventos'),
('Función especial Ballet Folklorico de México de Amalia Hernández.', 'Agrupación de eventos'),
('Los tres Reyes Magos, El Musical', 'Agrupación de eventos'),
('Galas del único y original Circo Atayde - 137 Aniversario', 'Agrupación de eventos'),
('Navidades en México. Ballet Folklorico de México de Amalia Hernández', 'Agrupación de eventos'),
('Bluey Diversión en Familia', 'Agrupación de eventos'),
('El Mago de Oz Musical', 'Agrupación de eventos'),
('Farandula 021 en Vivo', 'Agrupación de eventos'),
('Defendiendo al Cavernícola con César Bono', 'Agrupación de eventos'),
('Platanito Show', 'Agrupación de eventos'),
('"Un Cuento De Navidad, El Musical" Con Adal Ramones', 'Agrupación de eventos'),
('Ni tú, Ni Yo, El Musical', 'Agrupación de eventos'),
('La Bella Durmiente', 'Agrupación de eventos'),
('Moscow State Ballet "El Lago de los Cisnes', 'Agrupación de eventos'),
('Ballet de Kiev "El Lago de los Cisnes" De Viktor Ishchuk', 'Agrupación de eventos'),
('Clue', 'Agrupación de eventos'),
('Dios mío hazme viuda, por favor', 'Agrupación de eventos'),
('Pepe pelos, pelos experience.', 'Agrupación de eventos'),
('El Show de Platanito y Pipirin', 'Agrupación de eventos'),
('Enrollados Show En Vivo', 'Agrupación de eventos'),
('Brilla Fest 2025 Entrada General Sin Acceso al Show', 'Agrupación de eventos'),
('Brilla Fest 2025, Ingreso a partir de las 17:30 hrs.', 'Agrupación de eventos'),
('La Fabrica de Santa', 'Agrupación de eventos'),
('31 Minutos Radio Guaripolo II', 'Agrupación de eventos'),
('Formula 1 Gran Premio de la Ciudad de México', 'Formula 1 Gran Premio de la Ciudad de México'),
('ABB FIA Formula E Hankook Mexico City E-Prix 2026', 'ABB FIA Formula E Hankook Mexico City E-Prix 2026')
ON CONFLICT DO NOTHING;
